apiVersion: apps/v1
kind: Deployment
metadata:
  name: devstone-deployment
  labels:
    app: devstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devstone
  template:
    metadata:
      labels:
        app: devstone
    spec:
      containers:
      - name: devstone
        image: vtong24/devstone:latest
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: devstone-service
spec:
  type: NodePort
  selector:
    app: devstone
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008